/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import modelos.Cliente;
import presentadores.PresentadorTransferencias;
import vistas.interfaces.IvistaTransferenciasInterface;

/**
 *
 * @author nicol
 */
public class VistaTransferencias extends javax.swing.JFrame implements IvistaTransferenciasInterface {

    PresentadorTransferencias presentadorTransferencias;

    public VistaTransferencias() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Transferencias");
        presentadorTransferencias = new PresentadorTransferencias(this);
        presentadorTransferencias.inicializarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        DesdejComboBoxTransferencia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        HaciajComboBoxTransferencia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        MontojTextFieldTransferencia = new javax.swing.JTextField();
        TransferirjButton = new javax.swing.JButton();
        DesdejLabel = new javax.swing.JLabel();
        HaciajLabel = new javax.swing.JLabel();
        MontojLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        AltaClientesjMenuItem = new javax.swing.JMenuItem();
        MovimientosjMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Desde:");

        jLabel2.setText("Hacia:");

        jLabel3.setText("Monto:");

        TransferirjButton.setText("Transferir");
        TransferirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferirjButtonApretado(evt);
            }
        });

        jMenu2.setText("Funciones");

        AltaClientesjMenuItem.setText("Nuevo Cliente");
        AltaClientesjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaClientesjMenuItemApretado(evt);
            }
        });
        jMenu2.add(AltaClientesjMenuItem);

        MovimientosjMenuItem.setText("Movimientos");
        MovimientosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientosjMenuItemApretado(evt);
            }
        });
        jMenu2.add(MovimientosjMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DesdejComboBoxTransferencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HaciajComboBoxTransferencia, 0, 210, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(MontojTextFieldTransferencia)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesdejLabel)
                    .addComponent(HaciajLabel)
                    .addComponent(MontojLabel))
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TransferirjButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DesdejComboBoxTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DesdejLabel))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(HaciajComboBoxTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HaciajLabel))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(MontojTextFieldTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MontojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(TransferirjButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MovimientosjMenuItemApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientosjMenuItemApretado
        presentadorTransferencias.haciaMovimientos();
    }//GEN-LAST:event_MovimientosjMenuItemApretado

    private void AltaClientesjMenuItemApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaClientesjMenuItemApretado
        presentadorTransferencias.haciaAltaClientes();
    }//GEN-LAST:event_AltaClientesjMenuItemApretado

    private void TransferirjButtonApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferirjButtonApretado
        presentadorTransferencias.transferir();
    }//GEN-LAST:event_TransferirjButtonApretado

    public JComboBox<Cliente> getDesdejComboBoxTransferencia() {
        return DesdejComboBoxTransferencia;
    }

    public JComboBox<Cliente> getHaciajComboBoxTransferencia() {
        return HaciajComboBoxTransferencia;
    }

    public JTextField getMontojTextFieldTransferencia() {
        return MontojTextFieldTransferencia;
    }

    public JLabel getDesdejLabel() {
        return DesdejLabel;
    }

    public JLabel getHaciajLabel() {
        return HaciajLabel;
    }

    public JLabel getMontojLabel() {
        return MontojLabel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AltaClientesjMenuItem;
    private javax.swing.JComboBox<Cliente> DesdejComboBoxTransferencia;
    private javax.swing.JLabel DesdejLabel;
    private javax.swing.JComboBox<Cliente> HaciajComboBoxTransferencia;
    private javax.swing.JLabel HaciajLabel;
    private javax.swing.JLabel MontojLabel;
    private javax.swing.JTextField MontojTextFieldTransferencia;
    private javax.swing.JMenuItem MovimientosjMenuItem;
    private javax.swing.JButton TransferirjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tranferenciaRealizada() {
        JOptionPane.showMessageDialog(this, "transaccion realizada con exito", "ATENCION", JOptionPane.INFORMATION_MESSAGE);

        getMontojTextFieldTransferencia().setText("");
    }

    public void setErrorHacia(String error) {
        getHaciajComboBoxTransferencia().setBorder(new LineBorder(Color.RED));
        getHaciajLabel().setText(error);
        getHaciajLabel().setForeground(Color.RED);
    }

    public void setErrorMonto(String error) {
        getMontojTextFieldTransferencia().setBorder(new LineBorder(Color.RED));
        getMontojLabel().setText(error);
        getMontojLabel().setForeground(Color.RED);
    }

    public void limpiarErrores() {
        getMontojTextFieldTransferencia().setBorder(new LineBorder(Color.GRAY));
        getMontojLabel().setText("");
        getMontojLabel().setForeground(Color.GRAY);

        getHaciajComboBoxTransferencia().setBorder(new LineBorder(Color.GRAY));
        getHaciajLabel().setText("");
        getHaciajLabel().setForeground(Color.GRAY);

        getMontojTextFieldTransferencia().setBorder(new LineBorder(Color.GRAY));
        getMontojLabel().setText("");
        getMontojLabel().setForeground(Color.GRAY);
    }

    
    public void cargarClientes(Cliente[] clientes) {
        
        for (Cliente cliente : clientes) {

            getDesdejComboBoxTransferencia().addItem(cliente);

            getHaciajComboBoxTransferencia().addItem(cliente);

        }
    }

}
